service: lambda
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-west-2

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  findFirstPositive:
    handler: src/findFirstPositive/handler.findFirstPositive
    events:
      - httpApi:
          path: /
          method: post
  findPositiveSum:
    handler: src/findPositiveSum/handler.findPositiveSum
    events:
      - httpApi:
          path: /positive-sum
          method: post
  findN:
    handler: src/findN/handler.findN
    events:
      - httpApi:
          path: /find-n
          method: post
  dayOfYear:
    handler: src/dayOfYear/handler.dayOfYear
    events:
      - httpApi:
          path: /day
          method: get
  sortArr:
    handler: src/sortArr/handler.sortArr
    events:
      - httpApi:
          path: /sort
          method: post
